#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
script_src="$repo_root/ccusage_m_view.js"

if [[ ! -f "$script_src" ]]; then
  echo "ccusage_m_view.js not found at: $script_src" >&2
  exit 1
fi

# Resolve CODEX_HOME:
# - If set, use it
# - Else if ~/.codex exists, use it
# - Else default to ~/.codex and create it
codex_home="${CODEX_HOME:-}"
if [[ -z "$codex_home" ]]; then
  if [[ -n "${USERPROFILE:-}" ]] && command -v cygpath >/dev/null 2>&1; then
    codex_home="$(cygpath -u "$USERPROFILE")/.codex"
  else
    codex_home="$HOME/.codex"
  fi
fi
mkdir -p "$codex_home"

codex_home_for_node="$codex_home"
if command -v cygpath >/dev/null 2>&1; then
  codex_home_for_node="$(cygpath -m "$codex_home")"
fi

target="$codex_home/ccusage_m_view.js"
if [[ -f "$target" ]]; then
  cp -f "$target" "$target.bak-$(date +%Y%m%d_%H%M%S)"
fi
cp -f "$script_src" "$target"

choose_rc() {
  if [[ -f "$HOME/.zshrc" ]]; then
    echo "$HOME/.zshrc"
    return
  fi
  echo "$HOME/.bashrc"
}

rc_file="$(choose_rc)"
mkdir -p "$(dirname "$rc_file")"
touch "$rc_file"
cp -f "$rc_file" "$rc_file.bak-$(date +%Y%m%d_%H%M%S)"

marker="ccusage-codex-m"
begin="# >>> $marker >>>"
end="# <<< $marker <<<"

block="$begin
# ccusage-codex-m command family (generated by ccusage-codex-m/scripts/install.sh)
export CODEX_HOME=\"$codex_home_for_node\"

ccusage-codex-m() { node \"$codex_home_for_node/ccusage_m_view.js\" daily \"\$@\"; }
ccusage-codex-monthly() { node \"$codex_home_for_node/ccusage_m_view.js\" monthly \"\$@\"; }
ccusage-codex-open() { node \"$codex_home_for_node/ccusage_m_view.js\" sessions \"\$@\"; }
$end"

if grep -qF "$begin" "$rc_file" && grep -qF "$end" "$rc_file"; then
  echo "Profile already contains $marker block: $rc_file"
  echo "Run with FORCE=1 to replace it."
  if [[ "${FORCE:-}" == "1" ]]; then
    tmp="$(mktemp)"
    # Replace existing block between begin/end (inclusive).
    awk -v b="$begin" -v e="$end" -v repl="$block" '
      BEGIN { in=0 }
      $0==b { print repl; in=1; next }
      $0==e { in=0; next }
      in==0 { print }
    ' "$rc_file" > "$tmp"
    mv "$tmp" "$rc_file"
    echo "Replaced $marker block in: $rc_file"
  fi
else
  printf "\n%s\n" "$block" >> "$rc_file"
  echo "Updated profile: $rc_file"
fi

echo "Installed: $target"
echo "Next:"
echo "  1) source \"$rc_file\""
echo "  2) ccusage-codex-m"

