param(
  [string]$CodexHome = $env:CODEX_HOME,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Resolve-CodexHome {
  param([string]$Value)

  if (-not [string]::IsNullOrWhiteSpace($Value)) {
    try {
      return (Resolve-Path -LiteralPath $Value -ErrorAction Stop).Path
    } catch {
      return $Value
    }
  }

  $default = Join-Path $env:USERPROFILE ".codex"
  return $default
}

function Backup-FileIfExists {
  param([string]$Path)

  if (Test-Path -LiteralPath $Path) {
    $stamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $bak = "$Path.bak-$stamp"
    Copy-Item -LiteralPath $Path -Destination $bak -Force
    return $bak
  }
  return $null
}

function Ensure-ProfileFile {
  param([string]$ProfilePath)

  $dir = Split-Path -Parent $ProfilePath
  if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }
  if (-not (Test-Path -LiteralPath $ProfilePath)) {
    New-Item -ItemType File -Path $ProfilePath -Force | Out-Null
  }
}

function Ensure-BlockInProfile {
  param(
    [string]$ProfilePath,
    [string]$MarkerId,
    [string]$BlockText
  )

  $content = if (Test-Path -LiteralPath $ProfilePath) { Get-Content -LiteralPath $ProfilePath -Raw } else { "" }

  $begin = "# >>> $MarkerId >>>"
  $end = "# <<< $MarkerId <<<"

  if ($content -match [regex]::Escape($begin) -and $content -match [regex]::Escape($end)) {
    if ($Force) {
      # Replace existing block.
      $pattern = [regex]::Escape($begin) + ".*?" + [regex]::Escape($end)
      $newContent = [regex]::Replace($content, $pattern, $BlockText, [System.Text.RegularExpressions.RegexOptions]::Singleline)
      Set-Content -LiteralPath $ProfilePath -Value $newContent -Encoding utf8
      return "replaced"
    }
    return "exists"
  }

  $separator = if ($content.EndsWith("`r`n") -or $content.EndsWith("`n") -or $content.Length -eq 0) { "" } else { "`r`n" }
  $new = $content + $separator + $BlockText + "`r`n"
  Set-Content -LiteralPath $ProfilePath -Value $new -Encoding utf8
  return "added"
}

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $repoRoot

$scriptPath = Join-Path $repoRoot "ccusage_m_view.js"
if (-not (Test-Path -LiteralPath $scriptPath)) {
  throw "ccusage_m_view.js not found at: $scriptPath"
}

$codexHomeResolved = Resolve-CodexHome -Value $CodexHome
if (-not (Test-Path -LiteralPath $codexHomeResolved)) {
  New-Item -ItemType Directory -Path $codexHomeResolved -Force | Out-Null
}

$targetScript = Join-Path $codexHomeResolved "ccusage_m_view.js"
$bakScript = Backup-FileIfExists -Path $targetScript
Copy-Item -LiteralPath $scriptPath -Destination $targetScript -Force

$profilePath = $PROFILE
Ensure-ProfileFile -ProfilePath $profilePath
$bakProfile = Backup-FileIfExists -Path $profilePath

# Use forward-slash paths so Node can resolve consistently.
$codexHomeForNode = ($codexHomeResolved -replace '\\', '/')
$scriptForNode = "$codexHomeForNode/ccusage_m_view.js"

$marker = "ccusage-codex-m"
$block = @"
# >>> $marker >>>
# ccusage-codex-m command family (generated by ccusage-codex-m/scripts/install.ps1)
`$env:CODEX_HOME = `"$codexHomeResolved`"

function ccusage-codex-m { node $scriptForNode daily @args }
function ccusage-codex-monthly { node $scriptForNode monthly @args }
function ccusage-codex-open { node $scriptForNode sessions @args }
# <<< $marker <<<
"@

$profileStatus = Ensure-BlockInProfile -ProfilePath $profilePath -MarkerId $marker -BlockText $block

Write-Host "Installed: $targetScript"
if ($bakScript) { Write-Host "Backup:   $bakScript" }
Write-Host "Updated profile: $profilePath ($profileStatus)"
if ($bakProfile) { Write-Host "Profile backup:  $bakProfile" }
Write-Host ""
Write-Host "Next:"
Write-Host "  1) Restart PowerShell, or run: . `$PROFILE"
Write-Host "  2) Try: ccusage-codex-m"
